- name: install EPEL 
  yum:
    name: epel-release

- name: install unbound
  yum:
    name: unbound
    state: present
  become: true

- name: run unbound
  systemd:
    name: unbound
    state: started
  notify:
    - Restart unbound
