- name: install apt key
  apt_key:
    url: "https://repo.zabbix.com/zabbix-official-repo.key"
    keyring: "/etc/apt/trusted.gpg.d/zabbix-official-repo.gpg"
  when: ansible_os_family == "Debian"

- name: install apt repository
  apt_repository:
    repo: "deb {{ zabbix_repo_url[ansible_distribution] }} {{ ansible_distribution_release }} main"
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: install yum repository
  yum_repository:
    name: "{{ item.repo_name }}"
    file: zabbix
    description: "{{ item.repo_description | default('') }}"
    baseurl: "{{ item.repo_url }}"
    repo_gpgcheck: no
    gpgkey: "{{ item.gpg_key }}"
    gpgcheck: yes
    enabled: no
  with_items: "{{ zabbix_repos }}"
  when: ansible_os_family == "RedHat"
