- name: install yum repository
  yum_repository:
    name: "{{ item.repo_name }}"
    file: zabbix
    description: "{{ item.repo_description | default('') }}"
    baseurl: "{{ item.repo_url }}"
    repo_gpgcheck: no
    gpgkey: "{{ item.gpg_key }}"
    gpgcheck: yes
    enabled: no
  with_items: "{{ zabbix_repos }}"
  when: ansible_os_family == "RedHat"
