- hosts: all
  become: yes
  roles:
    - { role: disable_selinux, when: 'ansible_distribution in ("RedHat", "CentOS")' }
    - timezone
    - chrony
    - configure_dns_settings
    - install_common_pkg
