- name: add mysql8.0 repository
  yum:
    name: "{{ mysql80_repository }}"

- name: install mysql8.0
  yum:
    name: mysql-server
    update_cache: true
    state: latest

- name: set firewalld for MySQL
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item.port }}/{{ item.protocol }}"
    state: "{{ item.state }}"
    zone: "{{ item.zone }}"
  with_items:
    "{{ firewalld_entries }}"
