- name: install zabbix-agent
  include_tasks: "{{ ansible_os_family }}.yml"

- name: transfer zabbix config file
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - Restart zabbix-agent
