- name: Restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
  become: yes

- name: Restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted
  become: yes
