- include_vars: "{{ansible_distribution}}.yml"

- name: ensure install chrony
  package:
    name: chrony
    state: latest

- name: configure chrony
  template:
    src: chrony.conf.j2
    dest: "{{ chrony_path }}/chrony.conf"
  notify: restart chrony
