- name: make symlink of /etc/resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: configure DNS settings of /etc/systemd/resolv.conf
  template:
    src: ubuntu.resolv.conf.j2
    dest: /etc/systemd/resolved.conf
    mode: '0644'
    owner: root
    group: root
    backup: yes
  notify:
    - Restart systemd-resolved
