- name: configure unbound.conf
  template:
    src: centos.unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    mode: '0644'
    owner: root
    group: root
    backup: yes
  notify:
    - Restart unbound

- name: configure main.conf
  template:
    src: main.conf.j2
    dest: /etc/unbound/conf.d/main.conf
    mode: '0644'
    owner: root
    group: root
    backup: yes
  notify:
    - Restart unbound
