zabbix_repo_file_name: "zabbix"
zabbix_repos:
  - repo_name: "zabbix"
    repo_description: "Zabbix Official Repository - $basearch"
    repo_url: "{{ zabbix_repo_url[ansible_distribution + ansible_distribution_major_version] }}"
    gpg_key: "https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591"
  - repo_name: "zabbix-frontend"
    repo_description: "Zabbix Official Repository frontend - $basearch"
    repo_url: "{{ zabbix_repo_url[ansible_distribution + ansible_distribution_major_version] }}frontend"
    gpg_key: "https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591"
  - repo_name: "zabbix-debuginfo"
    repo_description: "Zabbix Official Repository debuginfo - $basearch"
    repo_url: "{{ zabbix_repo_url[ansible_distribution + ansible_distribution_major_version] }}debuginfo/"
    gpg_key: "https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591"
  - repo_name: "zabbix-non-supported"
    repo_description: "Zabbix Official Repository non-supported - $basearch"
    repo_url: "{{ zabbix_repo_url[ansible_os_family + '_non-supported'] }}"
    gpg_key: "https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX"

zabbix_repo_url:
  CentOS7: "http://repo.zabbix.com/zabbix/5.0/rhel/7/$basearch/"
  RedHat7: "http://repo.zabbix.com/zabbix/5.0/rhel/7/$basearch/"
  RedHat_non-supported: "http://repo.zabbix.com/non-supported/rhel/{{ ansible_distribution_major_version }}/$basearch/"
  RedHat8: "http://repo.zabbix.com/zabbix/5.0/rhel/8/$basearch/"
  Ubuntu18: "http://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1%2Bbionic_all.deb"
  Ubuntu20: "http://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb"
